[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "auction_house_keypair.json"

[programs.localnet]
auction_house="3B62xC9sdfT5i8bejPcGkBiDjxqqTgqNFPsMu5NztgcM"
bubblegum="BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"

[programs.mainnet]
auction_house="3B62xC9sdfT5i8bejPcGkBiDjxqqTgqNFPsMu5NztgcM"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "3B62xC9sdfT5i8bejPcGkBiDjxqqTgqNFPsMu5NztgcM"
program = "target/deploy/mpl_auction_house.so"

[[test.genesis]]
address = "qntmGodpGkrM42mN68VCZHXnKqDCT8rdY23wFcXCLPd"
program = "target/deploy/mpl_token_entangler.so"

[[test.genesis]]
address = "SaLeTjyUa5wXHnGuewUSyJ5JWZaHwz3TxqUntCE9czo"
program = "target/deploy/mpl_fixed_price_sale.so"

[[test.genesis]]
address = "gdrpGjVffourzkdDRrQmySw4aTHr8a3xmQzzxSwFD1a"
program = "target/deploy/mpl_gumdrop.so"

[[test.genesis]]
address = "hyDQ4Nz1eYyegS6JfenyKwKzYxRsCWCriYSAjtzP4Vg"
program = "target/deploy/mpl_hydra.so"

[workspace]
members = [
  "token-entangler/program",
  "token-metadata/program",
  "auction-house/program",
  "fixed-price-sale/program",
  "hydra/program",
  "bubblegum/program",
]
